# Generated by Django 5.2.1 on 2025-06-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='konut',
            old_name='baslik',
            new_name='konut_turu',
        ),
    ]
