# Generated by Django 5.2.1 on 2025-06-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0002_rename_baslik_konut_konut_turu'),
    ]

    operations = [
        migrations.AddField(
            model_name='konut',
            name='sahip_turu',
            field=models.CharField(choices=[('sahibinden', 'Sahibinden'), ('emlakci', 'Emlakçı')], default='sahibinden', max_length=20),
        ),
    ]
