# Generated by Django 5.2.1 on 2025-06-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0003_konut_sahip_turu'),
    ]

    operations = [
        migrations.AddField(
            model_name='konut',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='ilan_resimleri/'),
        ),
    ]
