# Generated by Django 5.2.1 on 2025-06-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0004_konut_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konut',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='konut_resimleri/'),
        ),
    ]
